version: "3.8"

services:
    postgres:
        image: postgres:11-alpine
        volumes:
            - D:\postgres11:/var/lib/postgresql/data
        networks:
            tmd-net:
                ipv4_address: 172.19.0.10

        environment:
            - POSTGRES_PASSWORD=tmd+123
            - POSTGRES_USER=tmdadm
            - POSTGRES_DB=tmd67
            - POSTGRES_HOST_AUTH_METHOD=trust
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

    gw-tmd67:
        image: gw-tmd67
        volumes:
            - C:\Users\albin\PycharmProjects\tmd67-compose\tmd67-gw\nginx\nginx.conf:/etc/nginx/conf.d/default.conf
            - C:\Users\albin\PycharmProjects\tmd67-compose\tmd67-gw\nginx\key.pem:/etc/nginx/conf.d/key.pem
            - C:\Users\albin\PycharmProjects\tmd67-compose\tmd67-gw\nginx\cert.pem:/etc/nginx/conf.d/cert.pem
            - C:\Users\albin\PycharmProjects\tmd67-compose\tmd67-gw\www:/var/www
        networks:
            tmd-net:
                ipv4_address: 172.19.0.11
        ports:
            - 8080:8080
            - 80:80
            - 443:443
            - 8000:8000
        depends_on:
            - api-tmd67

    api-tmd67:
        image: api-tmd67
        volumes:
            - C:\Users\albin\PycharmProjects\tmd67-compose\tmd67-be\:/workspaces/tmd67-be
        environment:
            - HOST_NAME=postgres
        networks:
            tmd-net:
                ipv4_address: 172.19.0.12
        depends_on:
            - postgres

networks:
  tmd-net:
    driver: bridge
    name: tmd-net
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16